"""add tenant_id to ingestion_jobs

Revision ID: 2429fd824a26
Revises: aef33da068c2
Create Date: 2026-03-23 10:02:03.582863

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '2429fd824a26'
down_revision = 'aef33da068c2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('extracted_contents', sa.Column('tenant_id', sa.UUID(), nullable=False))
    op.alter_column('extracted_contents', 'raw_text',
               existing_type=sa.TEXT(),
               type_=sa.String(length=1000000),
               existing_nullable=True)
    op.create_index(op.f('ix_extracted_contents_tenant_id'), 'extracted_contents', ['tenant_id'], unique=False)
    op.add_column('ingestion_jobs', sa.Column('tenant_id', sa.UUID(), nullable=False))
    op.add_column('ingestion_jobs', sa.Column('source_type', sa.String(length=50), nullable=True))
    op.add_column('ingestion_jobs', sa.Column('source_uri', sa.String(length=1000), nullable=True))
    op.add_column('ingestion_jobs', sa.Column('destination_type', sa.String(length=50), nullable=True))
    op.add_column('ingestion_jobs', sa.Column('destination_uri', sa.String(length=1000), nullable=True))
    op.create_index(op.f('ix_ingestion_jobs_tenant_id'), 'ingestion_jobs', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ingestion_jobs_tenant_id'), table_name='ingestion_jobs')
    op.drop_column('ingestion_jobs', 'destination_uri')
    op.drop_column('ingestion_jobs', 'destination_type')
    op.drop_column('ingestion_jobs', 'source_uri')
    op.drop_column('ingestion_jobs', 'source_type')
    op.drop_column('ingestion_jobs', 'tenant_id')
    op.drop_index(op.f('ix_extracted_contents_tenant_id'), table_name='extracted_contents')
    op.alter_column('extracted_contents', 'raw_text',
               existing_type=sa.String(length=1000000),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('extracted_contents', 'tenant_id')
    # ### end Alembic commands ###

