"""add tenant_id to ingestion_jobs

Revision ID: 354bc809a57d
Revises: 2429fd824a26
Create Date: 2026-03-23 10:12:41.089834

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '354bc809a57d'
down_revision = '2429fd824a26'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

