"""initial schema

Revision ID: c17702b17c4d
Revises: 
Create Date: 2026-03-25 13:35:20.032817

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'c17702b17c4d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingestion_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=True),
    sa.Column('source_uri', sa.String(length=1000), nullable=True),
    sa.Column('destination_type', sa.String(length=50), nullable=True),
    sa.Column('destination_uri', sa.String(length=1000), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingestion_jobs_session_id'), 'ingestion_jobs', ['session_id'], unique=False)
    op.create_table('chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('section_title', sa.String(length=500), nullable=True),
    sa.Column('heading_level', sa.SmallInteger(), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('lang_confidence', sa.Float(), nullable=False),
    sa.Column('chunk_strategy', sa.String(length=50), nullable=False),
    sa.Column('parent_chunk_id', sa.UUID(), nullable=True),
    sa.Column('topic', sa.String(length=64), nullable=True),
    sa.Column('doc_type', sa.String(length=64), nullable=True),
    sa.Column('entities', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('keywords', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['ingestion_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_chunk_id'], ['chunks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chunks_created_at'), 'chunks', ['created_at'], unique=False)
    op.create_index(op.f('ix_chunks_job_id'), 'chunks', ['job_id'], unique=False)
    op.create_index(op.f('ix_chunks_session_id'), 'chunks', ['session_id'], unique=False)
    op.create_index(op.f('ix_chunks_source_id'), 'chunks', ['source_id'], unique=False)
    op.create_table('extracted_contents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('raw_text', sa.String(length=1000000), nullable=True),
    sa.Column('pages', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tables', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('warnings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['ingestion_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extracted_contents_session_id'), 'extracted_contents', ['session_id'], unique=False)
    op.create_table('preprocessed_data',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False, comment='Copied from ingestion_jobs.session_id.'),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('content_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=True, comment='Copied from ingestion_jobs.filename.'),
    sa.Column('document_type', sa.String(length=50), nullable=True, comment='Copied from ingestion_jobs.document_type.'),
    sa.Column('source_type', sa.String(length=50), nullable=True, comment='Copied from ingestion_jobs.source_type. e.g. file_upload, s3, confluence, url, git.'),
    sa.Column('source_uri', sa.String(length=1000), nullable=True, comment='Copied from ingestion_jobs.source_uri.'),
    sa.Column('preprocessed_text', sa.Text(), nullable=True, comment='Clean text after the full preprocessing pipeline. This field feeds the Chunking Engine.'),
    sa.Column('preprocessed_pages', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='List of preprocessed page objects, each containing page_number, text, word_count, etc.'),
    sa.Column('language', sa.String(length=20), nullable=False, comment="Detected language (e.g. 'ENGLISH', 'SPANISH', 'UNKNOWN')"),
    sa.Column('lang_confidence', sa.Float(), nullable=False, comment='Language detection confidence score (0.0-1.0)'),
    sa.Column('status', sa.Enum('completed', 'skipped_dup', 'rejected', 'failed', name='preprocessstatus'), nullable=False, comment='completed | skipped_dup | rejected | failed'),
    sa.Column('error_message', sa.Text(), nullable=True, comment="Exception detail when status = 'failed'. Null otherwise."),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['extracted_contents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['ingestion_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_preprocessed_data_content_id'), 'preprocessed_data', ['content_id'], unique=False)
    op.create_index(op.f('ix_preprocessed_data_job_id'), 'preprocessed_data', ['job_id'], unique=False)
    op.create_index(op.f('ix_preprocessed_data_session_id'), 'preprocessed_data', ['session_id'], unique=False)
    op.create_index(op.f('ix_preprocessed_data_status'), 'preprocessed_data', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_preprocessed_data_status'), table_name='preprocessed_data')
    op.drop_index(op.f('ix_preprocessed_data_session_id'), table_name='preprocessed_data')
    op.drop_index(op.f('ix_preprocessed_data_job_id'), table_name='preprocessed_data')
    op.drop_index(op.f('ix_preprocessed_data_content_id'), table_name='preprocessed_data')
    op.drop_table('preprocessed_data')
    op.drop_index(op.f('ix_extracted_contents_session_id'), table_name='extracted_contents')
    op.drop_table('extracted_contents')
    op.drop_index(op.f('ix_chunks_source_id'), table_name='chunks')
    op.drop_index(op.f('ix_chunks_session_id'), table_name='chunks')
    op.drop_index(op.f('ix_chunks_job_id'), table_name='chunks')
    op.drop_index(op.f('ix_chunks_created_at'), table_name='chunks')
    op.drop_table('chunks')
    op.drop_index(op.f('ix_ingestion_jobs_session_id'), table_name='ingestion_jobs')
    op.drop_table('ingestion_jobs')
    # ### end Alembic commands ###

